workflows:
  android-build:
    name: Build StudentFlow Android (Capacitor)

    environment:
      node: latest

    scripts:
      - name: Install Node deps
        script: |
          npm ci

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
