workflows:
  android-build:
    name: Build StudentFlow Android (Capacitor)

    scripts:
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
