name: StudentFlow PWA Build
triggering:
  push:
    branches:
      - main

workflows:
  android-build:
    name: Build StudentFlow APK
    # PAS de instance_type = automatique gratuit
    
    scripts:
      - name: Install Bubblewrap
        script: |
          npm install -g @bubblewrap/cli
          
      - name: Build APK
        script: |
          bubblewrap init --manifest https://ton-url.netlify.app/manifest.json
          bubblewrap build
          
    artifacts:
      - app/build/outputs/apk/release/*.apk
