workflows:
  android-build:
    name: Build StudentFlow APK
    instance_type: linux_x2

    environment:
      vars:
        ANDROID_SDK_ROOT: /home/builder/android-sdk
        ANDROID_HOME: /home/builder/android-sdk

    scripts:
      - name: Install Java + tools
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          java -version

      - name: Install Android SDK cmdline-tools
        script: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip

          # IMPORTANT: le SDK veut un dossier "latest"
          mkdir -p latest
          mv cmdline-tools/* latest/

          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          yes | sdkmanager --licenses

          sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: Build Release APK
        script: |
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          cd StudentFlowTWA
          chmod +x gradlew
          ./gradlew :app:assembleRelease

    artifacts:
      - StudentFlowTWA/app/build/outputs/apk/release/*.apk
